### PR TITLE
DCC-5457. Renamed biomarker and surgery

### PR DESCRIPTION
**Pull request by slovit**

### CODE REVIEW

**Comment by slovit** [comment]
Before asking for a server redeployment `release_23` download data must be fixed.
Replace the following directories `BOCA-FR`, `BRCA-KR`, `ESAD-UK`, `SKCA-BR` in `/icgc/download/release_23/data` directory on the production HDFS cluster with ones from `/icgc/release/ICGC23/0/export/data` directory.

**Comment by slovit** [comment]
@btiernay reminding you to deploy this PR

**Comment by btiernay** [comment]
@slovit Much thanks! Happy New Year!

**Comment by btiernay** [comment]
@slovit Had to do this:

```shell
hdfs dfs -cp /icgc/download/release_23/headers/surgery.tsv.gz /icgc/download/release_23/headers/donor_surgery.tsv.gz
hdfs dfs -cp /icgc/download/release_23/headers/biomarker.tsv.gz /icgc/download/release_23/headers/donor_biomarker.tsv.gz
```

because it was like this:

```shell
dcc_dev@hcn-134:~$ hdfs dfs -ls /icgc/download/release_23/headers
Found 20 items
-rw-r--r--   3 dcc_dev supergroup         94 2016-12-01 01:20 /icgc/download/release_23/headers/biomarker.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        315 2016-12-01 01:20 /icgc/download/release_23/headers/cnsm.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        234 2016-12-01 01:20 /icgc/download/release_23/headers/donor.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        113 2016-12-01 01:20 /icgc/download/release_23/headers/donor_exposure.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        123 2016-12-01 01:20 /icgc/download/release_23/headers/donor_family.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        136 2016-12-01 01:20 /icgc/download/release_23/headers/donor_therapy.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        182 2016-12-01 01:20 /icgc/download/release_23/headers/exp_array.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        214 2016-12-01 01:20 /icgc/download/release_23/headers/exp_seq.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        333 2016-12-01 01:20 /icgc/download/release_23/headers/jcn.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        210 2016-12-01 01:20 /icgc/download/release_23/headers/meth_array.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        261 2016-12-01 01:20 /icgc/download/release_23/headers/meth_seq.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        252 2016-12-01 01:20 /icgc/download/release_23/headers/mirna_seq.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        178 2016-12-01 01:20 /icgc/download/release_23/headers/pexp.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        120 2016-12-01 01:20 /icgc/download/release_23/headers/sample.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        305 2016-12-01 01:20 /icgc/download/release_23/headers/sgv_controlled.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        246 2016-12-01 01:20 /icgc/download/release_23/headers/specimen.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        376 2016-12-01 01:20 /icgc/download/release_23/headers/ssm_controlled.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        354 2016-12-01 01:20 /icgc/download/release_23/headers/ssm_open.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        372 2016-12-01 01:20 /icgc/download/release_23/headers/stsm.tsv.gz
-rw-r--r--   3 dcc_dev supergroup        101 2016-12-01 01:20 /icgc/download/release_23/headers/surgery.tsv.gz
```

**Comment by btiernay** [comment]
Looks like `dcc-commons` was never released which contains the BIOMARKER to DONOR_BIOMARKER change :(

**Comment by slovit** [comment]
@btiernay You did not need to update headers. The instructions does not specify that.
`dcc-commons@4.3.9` version contains the renamed `biomarker` and `surgery`: https://github.com/icgc-dcc/dcc-download/pull/38/files#diff-600376dffeb79835ede4a0b285078036L238

**Comment by btiernay** [comment]
Sadly, it was required:

image

**Comment by btiernay** [comment]
Also, you made the code changes in common, so eventually this would have blown up:

https://github.com/icgc-dcc/dcc-common/blob/develop/dcc-common-core/src/main/java/org/icgc/dcc/common/core/model/DownloadDataType.java#L71

**Pull request merged**
